load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "jpov_interface",
    hdrs = [
        "camera.h",
        "input_snapshot.h",
        "render_command.h",
        "window_info.h",
    ],
    visibility = ["//visibility:public"],
)
